// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/paulagates/clean-arch-3/internal/entity"
	"github.com/paulagates/clean-arch-3/internal/event"
	"github.com/paulagates/clean-arch-3/internal/infra/database"
	"github.com/paulagates/clean-arch-3/internal/infra/web"
	"github.com/paulagates/clean-arch-3/internal/usecase"
	"github.com/paulagates/clean-arch-3/pkg/events"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/paulagates/clean-arch-3/pkg/events"
	_ "github.com/streadway/amqp"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewListedOrdersUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.ListOrdersUseCase {
	orderRepository := database.NewOrderRepository(db)
	ordersListed := event.NewOrdersListed()
	listOrdersUseCase := usecase.NewListOrdersUseCase(orderRepository, ordersListed, eventDispatcher)
	return listOrdersUseCase
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	webOrderHandler := web.NewWebOrderHandler(eventDispatcher, orderRepository, orderCreated)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, event.NewOrdersListed, wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)), wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventInterface), new(*event.OrdersListed)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))

var setOrdersListedEvent = wire.NewSet(event.NewOrdersListed, wire.Bind(new(events.EventInterface), new(*event.OrdersListed)))
