services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy  
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations
    command: [ "-path", "/migrations/", "-database", "mysql://root:root@tcp(mysql:3306)/orders", "up" ]
