### Criar múltiplos pedidos
POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id": "a",
    "price": 100.5,
    "tax": 0.5
}

POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id": "b",
    "price": 200.75,
    "tax": 1.25
}

POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json+

{
    "id": "c",
    "price": 50.0,
    "tax": 0.2
}

### Listar pedidos
GET http://localhost:8000/order

